image:
  - Visual Studio 2017

environment:
  matrix:
    - var1: first
    
    - var1: second

build_script:
  - set aaa=aaaa
  - set bbb=bbbb
  
  - echo original aaa = %aaa%
  
  - set aaa=
  - echo empty 01 aaa = %aaa%
  
  - set "aaa="
  - echo empty 01 aaa = %aaa%

  - set aaa=%bbb:~0,0%
  - echo empty 02 aaa = %aaa%

  - set aaa=%bbb:bbbb=%
  - echo empty 03 aaa = %aaa%

  - ccc: cccc
  - ddd: dddd
  
  - echo ccc1=%ccc%
  - echo ccc2=$(ccc)

  - echo Building  %var1%
  
